<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.MetadataNotifier</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.MetadataNotifier</AssemblyName>
    <Version>1.1.0.1</Version>
    <AssemblyVersion>1.1.0.1</AssemblyVersion>
    <FileVersion>1.1.0.1</FileVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisMode>AllDisabledByDefault</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.*" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.*" />
    <PackageReference Include="Jellyfin.Database.Implementations" Version="10.11.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

</Project>
